### ISSUE TITLE
Azure via client/secret id and value

### ISSUE THREAD

**Issue by lzap** [RedHatQE/cloudwash#48]
Hello,

my Azure personal account is protected, just like all my cloud accounts, with 2FA. Cloudwash is unable to use that and it would be useless as I want to automate the process.

Is it possible to configure Azure account via client/secret id/value, like applications are normally supposed to be configured?

Thanks.

**Comment by jyejare** [comment]
Hello @lzap :

Thanks for opening the issue, have following questions for you so that I could understand the issue in deep.

> my Azure personal account is protected, just like all my cloud accounts, with 2FA. Cloudwash is unable to use that and it would be useless as I want to automate the process.

So would you like cloudwash to use 2FA for interacting with Azure for clean-up apart from the current password-based auth ?

> Is it possible to configure the Azure account via client/secret id/value, like applications are normally supposed to be configured?

Yes, its possible to configure with client-id and secret-id. The username and password in settings file are nothing but client and secret ids respectively .

**Comment by lzap** [comment]
Hey, no, it needs to use a regular application access using client/secret values instead of login/password.

**Comment by omkarkhatavkar** [comment]
@lzap if do you mean the 2FA using the TOTP token? this can be easily implemented in the cloudwash if you have the TOTP secret, here is the example https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/destructive/test_ldap_authentication.py#L116, if you think this what you wanted, we can add that feature.

**Comment by lzap** [comment]
Hey, there are multiple ways how to sign into Azure, one of being using client/secret value which you can generate:

https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal

Then no password or 2FA is needed.

I was trying to say I cannot use username/password beacuse my account is protected via 2FA. I am looking for ways to authorize via a client secret.

**Comment by jyejare** [comment]
@lzap @omkarkhatavkar Cloudwash 1.0.1 release changes the names of the settings so that they won't be confused anymore. We had confusion about Azure settings with auth fields like username/password, but that was nothing but client_id and secret_id.

So now @lzap you should be able to feed the client_id and secret_id(Application Secret created using https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#option-2-create-a-new-application-secret) in the azure settings file https://github.com/RedHatQE/cloudwash/blob/master/settings.yaml.template#L28-L29

**Comment by lzap** [comment]
Fantastic, sorry for the noise then :-) When I tried it was not working, I had my secret incorrectly I guess. Will try again soon, thanks!

**Comment by jyejare** [comment]
Thanks @lzap , I shall close this now! Please feel free to reopen if problem persists.
